#!/usr/bin/python3
import os
import sys
argv = sys.orig_argv
name = argv[2].removesuffix('.cpp')
os.system(
    f'clang++ {name}.cpp -std=c++20 -lassimp -lfmt -lyaml-cpp -fopenmp -ffast-math `sdl2-config --cflags --libs` -O3 -march=native -g -o build/{name} && build/{name}' if len(argv) > 2 else '')
